# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fce60026ea1f76b250501312c0c291dbf4586fcdf83b1476fb85e577c0ba3780fc8aa64da6f7366cd4bea7422ed25387268c5406253498c361af232db18bd7f6

test:
  secret_key_base: 085a8e13d8ee11c234566efa9e2208270912877447b968a8b52639605799c888f761da862e9e4db51ab146403c4b9102d1193016a9ad20bf914961c3b2fb748f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
